version: '2.0'
services:
  points:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: "points_postgres"
    ports:
      - "5432:5432"
    volumes:
      - points_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
volumes:
  points_dbdata:
